# docker-compose.mcp.yml
version: '3.8'

services:
  mcp-atlassian:
    image: ghcr.io/sooperset/mcp-atlassian:latest
    container_name: mcp-atlassian
    restart: unless-stopped
    ports:
      - "9000:9000"
    env_file:
      - .env.atlassian
    command: ["--transport", "streamable-http", "--port", "9000", "-vv"]

  context7:
    image: mcp/context7:latest
    container_name: mcp-context7
    restart: unless-stopped
    ports:
      - "9021:8080"
    command: []


  serena:
    image: ghcr.io/oraios/serena:latest
    container_name: mcp-serena
    restart: unless-stopped
    ports:
      - "9121:9121"
      - "24282:24282"
    volumes:
      - /Users/yohan/git/soludev:/workspaces/projects/soludev
    command: ["serena", "start-mcp-server", "--transport", "streamable-http", "--port", "9121", "--host", "0.0.0.0"]